import {Lexend} from 'next/font/google';
import {AuthProvider} from '@/src/context/AuthContext';

import Header from '../components/layout/header/Header';
import Footer from '../components/layout/footer/Footer';
import SonnerToast from '../components/libraries/sonnerToast/SonnerToast';
import NextNprogress from '../components/libraries/nextNprogress/NextNprogress';

import './globals.css';

const lexend = Lexend({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={`${lexend.className} bg-[#101827]`}>
        <AuthProvider>
          <NextNprogress>
            <main className='flex flex-col min-h-screen'>
              <Header />
              <div className='flex-1'>
                {children} <SonnerToast />
              </div>
              <Footer />
            </main>
          </NextNprogress>
        </AuthProvider>
      </body>
    </html>
  );
}
